#!/usr/bin/env bash
# One-click deployment of the server visualization stack.
#
# Designed to be run via:
#   sh -c "$(curl -fsSL https://raw.githubusercontent.com/DiscoverRobotics/gpu_monitor/main/server/install.sh)"
#
# Materializes docker-compose.yml + prometheus.yml + grafana provisioning
# under ${INSTALL_DIR} (default: $(pwd)/gpu-monitor-server) and brings up:
#   - Prometheus on :${PROMETHEUS_PORT:-9090} with --web.enable-remote-write-receiver
#   - Grafana    on :${GRAFANA_PORT:-3000}     with the Prometheus datasource auto-provisioned
#
# Idempotent: re-running regenerates configs and recreates containers as needed.
set -euo pipefail

PROMETHEUS_PORT="${PROMETHEUS_PORT:-9090}"
GRAFANA_PORT="${GRAFANA_PORT:-3000}"
GRAFANA_ADMIN_USER="${GRAFANA_ADMIN_USER:-admin}"
GRAFANA_ADMIN_PASSWORD="${GRAFANA_ADMIN_PASSWORD:-admin}"
INSTALL_DIR="${INSTALL_DIR:-$(pwd)/gpu-monitor-server}"

say()   { printf '\033[1;36m[server]\033[0m %s\n' "$*"; }
warn()  { printf '\033[1;33m[server]\033[0m %s\n' "$*" >&2; }
fail()  { printf '\033[1;31m[server]\033[0m %s\n' "$*" >&2; exit 1; }

# 1. Docker / Compose — auto-install if missing.
install_docker() {
  say "docker not found — installing via official convenience script ..."
  curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
  sh /tmp/get-docker.sh
  rm -f /tmp/get-docker.sh
  # allow current user to run docker without sudo (takes effect on next login)
  if [ "$(id -u)" -ne 0 ] && ! groups | grep -qw docker; then
    sudo usermod -aG docker "$(whoami)" || true
  fi
  # make sure the daemon is running
  if command -v systemctl >/dev/null 2>&1; then
    sudo systemctl enable --now docker
  fi
  command -v docker >/dev/null 2>&1 \
    || fail "docker installation failed — please install manually: https://docs.docker.com/engine/install/"
  say "docker installed successfully."
}

install_docker_compose() {
  say "docker compose not found — installing the v2 plugin ..."
  local compose_version="v2.29.2"
  local arch
  arch="$(uname -m)"
  case "${arch}" in
    x86_64)  arch="x86_64" ;;
    aarch64|arm64) arch="aarch64" ;;
    *) fail "unsupported architecture: ${arch}" ;;
  esac
  local dest="${DOCKER_CONFIG:-$HOME/.docker}/cli-plugins"
  mkdir -p "${dest}"
  curl -fsSL "https://github.com/docker/compose/releases/download/${compose_version}/docker-compose-linux-${arch}" \
    -o "${dest}/docker-compose"
  chmod +x "${dest}/docker-compose"
  docker compose version >/dev/null 2>&1 \
    || fail "docker compose installation failed — please install manually: https://docs.docker.com/compose/install/"
  say "docker compose installed successfully."
}

command -v docker >/dev/null 2>&1 || install_docker

if docker compose version >/dev/null 2>&1; then
  COMPOSE=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE=(docker-compose)
else
  install_docker_compose
  COMPOSE=(docker compose)
fi

# 2. Materialize config files.
say "writing config to ${INSTALL_DIR} ..."
mkdir -p "${INSTALL_DIR}/grafana/provisioning/datasources"
cd "${INSTALL_DIR}"

cat > docker-compose.yml <<'YAML'
# Server visualization stack — generated by install.sh; re-running overwrites this.
services:
  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: gpu-monitor-server-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-remote-write-receiver
      - --web.enable-lifecycle
      - --web.listen-address=:9090
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"

  grafana:
    image: grafana/grafana:10.4.2
    container_name: gpu-monitor-server-grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "${GRAFANA_PORT:-3000}:3000"

volumes:
  prom-data:
  grafana-data:
YAML

cat > prometheus.yml <<'YAML'
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  external_labels:
    role: server

# GPU nodes push their samples via remote_write to /api/v1/write
# (enabled by --web.enable-remote-write-receiver). The only local
# scrape target is Prometheus itself, for stack-health visibility.
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
YAML

cat > grafana/provisioning/datasources/prometheus.yml <<'YAML'
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
YAML

# 3. Bring containers up.
say "starting prometheus and grafana ..."
PROMETHEUS_PORT="${PROMETHEUS_PORT}" \
GRAFANA_PORT="${GRAFANA_PORT}" \
GRAFANA_ADMIN_USER="${GRAFANA_ADMIN_USER}" \
GRAFANA_ADMIN_PASSWORD="${GRAFANA_ADMIN_PASSWORD}" \
  "${COMPOSE[@]}" up -d

# 4. Wait for Prometheus.
say "waiting for prometheus /-/ready on :${PROMETHEUS_PORT} ..."
prom_ok=0
for i in {1..30}; do
  if curl -fsS --max-time 2 "http://127.0.0.1:${PROMETHEUS_PORT}/-/ready" -o /dev/null; then
    prom_ok=1; break
  fi
  sleep 1
done
[ "${prom_ok}" = 1 ] || warn "prometheus did not become ready in 30s — check 'docker compose logs prometheus'."

# 5. Confirm remote-write receiver is on.
flags_json="$(curl -fsS --max-time 5 "http://127.0.0.1:${PROMETHEUS_PORT}/api/v1/status/flags" 2>/dev/null || true)"
if echo "${flags_json}" | grep -q '"web.enable-remote-write-receiver":"true"'; then
  say "remote-write receiver is enabled — POST samples to /api/v1/write."
else
  warn "remote-write receiver flag NOT reported — check the prometheus container's command line."
fi

# 6. Wait for Grafana.
say "waiting for grafana /api/health on :${GRAFANA_PORT} ..."
graf_ok=0
for i in {1..60}; do
  health="$(curl -fsS --max-time 2 "http://127.0.0.1:${GRAFANA_PORT}/api/health" 2>/dev/null || true)"
  if echo "${health}" | grep -q '"database": "ok"'; then
    graf_ok=1; break
  fi
  sleep 1
done
[ "${graf_ok}" = 1 ] || warn "grafana did not become healthy in 60s — check 'docker compose logs grafana'."

cat <<EOF

================================================================
  Server visualization stack is up.

  Install dir: ${INSTALL_DIR}
  Prometheus:  http://127.0.0.1:${PROMETHEUS_PORT}
               remote_write endpoint: http://127.0.0.1:${PROMETHEUS_PORT}/api/v1/write
  Grafana:     http://127.0.0.1:${GRAFANA_PORT}   (login: ${GRAFANA_ADMIN_USER} / ${GRAFANA_ADMIN_PASSWORD})

  On each GPU node, point the agent at this host:
    sh -c "\$(curl -fsSL https://raw.githubusercontent.com/DiscoverRobotics/gpu_monitor/main/client/install.sh)" -- \\
      --PROMETHEUS_URL http://<this-host>:${PROMETHEUS_PORT} \\
      --GRAFANA_URL    http://<this-host>:${GRAFANA_PORT}
================================================================
EOF
